### ISSUE TITLE
auto line break fix

### ISSUE THREAD

**Issue by Caravanr54545** [OneMoreGres/ScreenTranslator#103]
Hi
Can added auto line break fix?
Example, normal text:

"The treasure chest is painted with stars and cosmic symbols in a green luminescent chemical that has not faded with the passage of the years."

screentranslator get:

The treasure chest is painted with
stars and cosmic symbols in a green
luminescent chemical that has not
faded with the passage of the years.

The deepl translator make worse translation, with bad line break. 

thanks

**Comment by OneMoreGres** [comment]
There are several similar issues. One still open (#69).

In short: you can add manual correction from end-of-line character ('\n') to, say, space (' ') in the settings.
Maybe someday there will be more intelligent/convenient workaround.

Closing due to duplicate. You can add comment here or in the open issue
