### ISSUE TITLE
Deepl не переводит

### ISSUE THREAD

**Issue by UniqueTiger** [OneMoreGres/ScreenTranslator#147]
Первый раз переводит нормально, но если повторно начать что-то переводить через Deepl то пишет подобное:

userscript:deepl.js: 20 start translate Students en ru
userscript:deepl.js: 50 Uncaught TypeError: Cannot read property 'innerText' of null 

и больше не переводит текст. 

Но если открыть окно с переводчиком и самостоятельно удалить англ текст, то он снова сможет один раз перевести.
Он почему-то не может вписать новый текст для перевода в переводчик.

**Comment by RedCapcha** [comment]
Та же проблема, это самый хороший переводчик, но теперь он не работает.

**Comment by RedCapcha** [comment]
Дублирую сюда то что написал разработчику на почту.
Windows10 PRO win64 
Сломалась интеграция переводчика DeepL. При запуске приложения переводит текст 1 раз, после чего перестаёт работать. В окне переводчика обнаружил следующее:
en ru
userscript:deepl.js: 64 setting url https://www.deepl.com/translator#en/ru/She's%20a%20young%20adult%20female%20of%20the%20Half-Breed%20Fox%20race.%20%20Her%20blond%20hair%20falls%20down%20to%20just%20below%20her%20neck.%20It%20is%20combed%20into%20a%20single%20braid.%20Her%20eyes%20are%20brown.%20She%20has%20vertical%2C%20animalistic%20pupils.%20She%20has%20a%20pair%20of%20long%20expressive%20fox%20ears.%20Her%20skin%20is%20a%20tanned%20bronze%20color.%20She%20has%20a%20large%2C%20fluffy%20fox%20tail.%20She%20is%20quite%20tall%20compared%20to%20the%20average%20person.%20%20Her%20nice%2C%20perky%20breasts%20are%20firm%20and%20inviting.%20She%20has%20a%20pleasantly%20plump%2C%20heart-shaped%20ass%20that%20jiggles%20enticingly%20with%20each%20step.%20She%20has%20a%20normal%20pussy%20below%20her%20waist.%20Her%20ass%20is%20trained%20enough%20for%20penetration.%20%20Penney%20is%20your%20slave%20and%20must%20obey%20your%20orders%20by%20law.
https://static.deepl.com/js/translator_late.min.$713de7.js: 2 DeepL Translator 
https://static.deepl.com/js/translator_late.min.$713de7.js: 2 Uncaught TypeError: Cannot read property 'appendChild' of null
https://static.deepl.com/js/translator_late.min.$713de7.js: 2 Welcome to DeepL.com!
https://static.deepl.com/js/translator_early.min.$1064bc.js: 1 Module already defined 'FeatureManager'
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Sending to DAP went wrong. [object Object]
https://static.deepl.com/js/utils.chunk.$ff90f2.js: 2 Uncaught (in promise) Sending to DAP went wrong.
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Sending to DAP went wrong. [object Object]
https://static.deepl.com/js/utils.chunk.$ff90f2.js: 2 Uncaught (in promise) Sending to DAP went wrong.
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Sending to DAP went wrong. [object Object]
https://static.deepl.com/js/utils.chunk.$ff90f2.js: 2 Uncaught (in promise) Sending to DAP went wrong.
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Module already defined 'LMT_UI_SystemNotification'
https://static.deepl.com/js/sentry.min.$60c602.js: 2 [FeatureManager.defineType] /translator/core/selectLangUI is already defined!
https://static.deepl.com/js/sentry.min.$60c602.js: 2 [dlTexts] Text not found: 'docTrans/translator.docTransTab.document'
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Sending to DAP went wrong. [object Object]
https://static.deepl.com/js/utils.chunk.$ff90f2.js: 2 Uncaught (in promise) Sending to DAP went wrong.
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Sending to DAP went wrong. [object Object]
https://static.deepl.com/js/utils.chunk.$ff90f2.js: 2 Uncaught (in promise) Sending to DAP went wrong.
[ДАЛЕЕ ИДЁТ ТЕКСТ КОТОРЫЙ ПЫТАЛСЯ ПЕРЕВЕСТИ]
0 Autofocus processing was blocked because a document already has a focused element.

**Comment by RedCapcha** [comment]
Копирую сюда то что писал разработчику на почту.
Windows10 PRO win64 
Сломалась интеграция переводчика DeepL. При запуске приложения переводит текст 1 раз, после чего перестаёт работать. В окне переводчика обнаружил следующее:
en ru
userscript:deepl.js: 64 setting url 
[ТЕКСТ]
https://static.deepl.com/js/translator_late.min.$713de7.js: 2 DeepL Translator 
https://static.deepl.com/js/translator_late.min.$713de7.js: 2 Uncaught TypeError: Cannot read property 'appendChild' of null
https://static.deepl.com/js/translator_late.min.$713de7.js: 2 Welcome to DeepL.com!
https://static.deepl.com/js/translator_early.min.$1064bc.js: 1 Module already defined 'FeatureManager'
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Sending to DAP went wrong. [object Object]
https://static.deepl.com/js/utils.chunk.$ff90f2.js: 2 Uncaught (in promise) Sending to DAP went wrong.
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Sending to DAP went wrong. [object Object]
https://static.deepl.com/js/utils.chunk.$ff90f2.js: 2 Uncaught (in promise) Sending to DAP went wrong.
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Sending to DAP went wrong. [object Object]
https://static.deepl.com/js/utils.chunk.$ff90f2.js: 2 Uncaught (in promise) Sending to DAP went wrong.
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Module already defined 'LMT_UI_SystemNotification'
https://static.deepl.com/js/sentry.min.$60c602.js: 2 [FeatureManager.defineType] /translator/core/selectLangUI is already defined!
https://static.deepl.com/js/sentry.min.$60c602.js: 2 [dlTexts] Text not found: 'docTrans/translator.docTransTab.document'
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Sending to DAP went wrong. [object Object]
https://static.deepl.com/js/utils.chunk.$ff90f2.js: 2 Uncaught (in promise) Sending to DAP went wrong.
https://static.deepl.com/js/sentry.min.$60c602.js: 2 Sending to DAP went wrong. [object Object]
https://static.deepl.com/js/utils.chunk.$ff90f2.js: 2 Uncaught (in promise) Sending to DAP went wrong.
[ДАЛЕЕ ИДЁТ ТЕКСТ КОТОРЫЙ ПЫТАЛСЯ ПЕРЕВЕСТИ]
0 Autofocus processing was blocked because a document already has a focused element.

**Comment by OneMoreGres** [comment]
На днях посмотрю

**Comment by OneMoreGres** [comment]
Подправил

**Comment by RedCapcha** [comment]
Сейчас проверим

**Comment by RedCapcha** [comment]
Первый запрос опять выдал ошибку, но последующие работают

**Comment by UniqueTiger** [comment]
Все работает, спасибо.
