### ISSUE TITLE
Any recommend guides/tutorials for building this project on windows?

### ISSUE THREAD

**Issue by 314pies** [OneMoreGres/ScreenTranslator#22]
I am interested in this project and want to do some contribution if possible.
Is there any guides/tutorials for building the project on windows so I can have a quicker start?

I mostly use c# and node.js at work and aren't familiar with typical c++ program development workflows, any guides or recommendation(such as: which compiler/IDE , how to install dependencies...etc) for setting up the project will be highly appreciated 🙂!

**Comment by OneMoreGres** [comment]
I'm currently in a middle of a major refactoring of the project, so right now is not the best time to contribute :)
I recommend to wait until I push rescent changes before starting to explore the code.

There are some scripts to build dependencies [here](https://github.com/OneMoreGres/ScreenTranslator/blob/master/scripts) but they are quite outdated and are a part of this refactoring.

I use Qt Creator to develop c++ apps.
To build the app simply open the `.pro` file, select the build kit (a combination of the Qt framework version and the compiler version) and then build a project (Ctrl+B or via the menus).
The Qt framework and Qt Creator can be downloaded from [here](https://download.qt.io/official_releases/online_installers/).
However this app requires some Qt modules that do not ship with the rescent Qt versions (and this is a part of a refactoring too :) )

According to you experience with javascript you may be interested in writing/editing translation scripts.
These are js scripts that are injected into web site pages to perform translation queries and parse the results.
Yu can look at them in the `translators` folder (but there is a refactoring, remember).

Anyway if you want to implement some completely new feature, consider opening the issue first (if there are no such already) to discuss it.
It would help to prevent situations when your PR is rejected due to mismatch in our project visions.

**Comment by 314pies** [comment]
Sure, I'll always discuss and check the objective before start working on a new feature.  Can't wait for the refactor done :)
Will there be any tools be used for managing tasks?  (sth like: [github project](https://github.com/OneMoreGres/ScreenTranslator/projects), Trello...)

**Comment by 314pies** [comment]
Another question here,
I just try to build the project with Qt5.5.1(both mingw492 and msvc version)，but got this error,
> ("tesseract/baseapi.h: No such file or directory")

Any recommend guides for installing dependency?

**Comment by OneMoreGres** [comment]
About task managing. Simple github issues will be fine for a start.
About missing include. Dependency build/install scripts are being refactored too, so they may not work now (they've been tested 2 years ago).
Can't say anything concrete about the error on the screenshot. Looks like something wrong with encoding or the compiler version. I'll be able to say more when I start porting scripts for Windows.

**Comment by 314pies** [comment]
ok... will try to figure out at my spare time 🤔

**Comment by OneMoreGres** [comment]
I've just pushed the branch with the current WIP state. Many things not work, but it compiles with rescent Qt version and there are updated build scripts in share/ci (you need to set OS env to win32/win64 or edit it in config.py)

**Comment by 314pies** [comment]
Awesome, will check it out later!

**Comment by OneMoreGres** [comment]
There is a fully working CI scripts for win/linux in `share/ci`. Closing the issue
