### ISSUE TITLE
Debug functioning

### ISSUE THREAD

**Issue by CommicKick69ing** [OneMoreGres/ScreenTranslator#8]
When debug is ativated only a white screen appears.

**Comment by OneMoreGres** [comment]
Yes. Debug mode just opens the internal web browser, which it uses to get the translation results from online services. It will be filled with data when you start translating something using the page-based translation provider (in contrast to API-based).
Does it works for you as I described?

**Comment by CommicKick69ing** [comment]
no

**Comment by OneMoreGres** [comment]
Do you have any translation services enabled in settings (which ones if yes)? Does the auto translation option turned on? What's your operation system? It's quite strange that you don't have anything in debug mode, since in your your previous issues you said that you do have a translation, but it's impossible wwithout filling debug mode's window (for page-based translation services).
